---
sudo: required

language: c

services:
  - docker

before_install:
  - docker build -t atgreen/labdroid-vault .

script:
  -

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push atgreen/labdroid-vault;
    fi

